//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSTOK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_Satislar
    {
        public int SatisId { get; set; }
        [Required(ErrorMessage ="ÜRÜN ADI BOÞ GEÇÝLMEZ...")]
        public Nullable<int> Urun { get; set; }
        [Required(ErrorMessage ="MÜÞTERÝ ADI SOYADI BOÞ GEÇÝLMEZ...")]
        public Nullable<int> Musteri { get; set; }

        public Nullable<byte> Adet { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
    
        public virtual Tbl_Musteri Tbl_Musteri { get; set; }
        public virtual Tbl_Urunler Tbl_Urunler { get; set; }
    }
}
